### ISSUE TITLE
Fix  Entity Type References on merge

### ISSUE THREAD

**Issue by CNAChino** [graph-quilt/graphql-orchestrator-java#107]
**Is your feature request related to a problem? Please describe.**

After entity type merging, some fields refer to the entity extension type object and some to Base Entity Type.  All type references should be on the merged Entity Type

**Describe the solution you'd like**

In XtextGraphFolder, use Xtext's `UsageCrossReferencer` to update type references on the operation  (Query, Mutation, Subscription).   References to Type extension should be replaced with the base type since, the current algorithm, extensions are merged to the base type.

**Comment by bhavinshah7** [comment]
Already [fixed](https://github.com/graph-quilt/graphql-orchestrator-java/blob/4d36e1801a5a6a7925d49303fa6251bc9caa3ece/src/main/java/com/intuit/graphql/orchestrator/schema/fold/UnifiedXtextGraphFolder.java#L177-L194)
