### ISSUE TITLE
ServiceDataFetcherTest.java is not implemented

### ISSUE THREAD

**Issue by CNAChino** [graph-quilt/graphql-orchestrator-java#109]
**Is your feature request related to a problem? Please describe.**

Test case in ServiceDataFetcher's unit test class is currently commented.  Need to refactor and make test passing

**Comment by SuchhandaDas** [comment]
@ashpak-shaikh I can take this issue up

**Comment by Suresh9293** [comment]
Hi @CNAChino as there is no active PR can you assign it to me? i was able to fix it

**Comment by Suresh9293** [comment]
PR: https://github.com/graph-quilt/graphql-orchestrator-java/pull/134
