### ISSUE TITLE
Optimize outgoing query.

### ISSUE THREAD

**Issue by ashpak-shaikh** [graph-quilt/graphql-orchestrator-java#125]
**Is your feature request related to a problem? Please describe.**

When the downstream queries are batched, there are multiple nodes in the query depending on where the query is merged.
Example 
```
query {
foo { bar { ..} }
foo { abc {..} }
}
```

**Describe the solution you'd like**

Ideally, when a query goes out of the orchestrator, it should be optimized graphql query like 
```
query {
foo { abc { ..}  bar {...} }
}
```

**Additional context**

Preprocess the query before going out. 
Starting point -> https://github.com/graph-quilt/graphql-orchestrator-java/blob/master/src/main/java/com/intuit/graphql/orchestrator/batch/GraphQLServiceBatchLoader.java#L155

**Comment by littleBuddhaa** [comment]
@ashpak-shaikh  I'd like to work on this

**Comment by littleBuddhaa** [comment]
@ashpak-shaikh is there a unit test written already that replicates this problem?

**Comment by ashpak-shaikh** [comment]
there should be but have to find one, take a look at this case 

Service A
```
type Query {
  a: A
}

type A {
  b: B
  c: C
}

type C { leaf: String }
type B { leaf: String }
```

Service B
```
type Query {
  a: A
}

type A {
  d: D
}

type D { leaf: String }
```

Make this query 

```
query {
   a {
     b 
     c  
     d 
    }
}
```

Query to service A should be 
```
query {
   a { b }
   a { c }
}
```

**Comment by littleBuddhaa** [comment]
@ashpak-shaikh  please review this https://github.com/graph-quilt/graphql-orchestrator-java/pull/133
