### ISSUE TITLE
Replace Junit/AssertJ tests with Spock Framework tests

### ISSUE THREAD

**Issue by bhavinshah7** [graph-quilt/graphql-orchestrator-java#127]
Migrate unit tests to use Spock framework. Some tests were migrated [here](https://github.com/intuit/graphql-orchestrator-java/pull/8/files) for reference. 

* Tests in groovy are easier to read. We don't need to offload our queries into separate resource files like in Java. 
def query = """
query {
}
"""

* More meaningful and easier to read method names
def "should produce result"() { }

* Easier to write (implicit types, given/when/then)

**Comment by rishu1601** [comment]
Hi @ashpak-shaikh @bhavinshah7 I am willing to take up the issue.
