### ISSUE TITLE
Support for List type merging

### ISSUE THREAD

**Issue by rajankit296** [graph-quilt/graphql-orchestrator-java#155]
We have gone thought the docs 
https://github.com/graph-quilt/graphql-orchestrator-java
https://github.com/graph-quilt/graphql-orchestrator-java

but did not get any details how to fetch data for two services with same unique id.
Getting merging exception.

We have two Services
Service 1  Schema:

`type Query { resourceType: [ResourceType] }

type ResourceType {
    name : String # unique key
    title: String
}`

Service 2 Schema:
`type Query { resourceType: [ResourceType] }

type ResourceType {
   name : String # unique key
    version: String 
    description: String
}`

Exception
`threw exception [Request processing failed; nested exception is com.intuit.graphql.orchestrator.schema.transform.FieldMergeException: Nested fields (parentType:Query, field:resourceType) are not eligible to merge. Reason: Type [name:ResourceType, type:, description:] is not an ObjectType] with root cause

com.intuit.graphql.orchestrator.schema.transform.FieldMergeException: Nested fields (parentType:Query, field:resourceType) are not eligible to merge. Reason: Type [name:ResourceType, type:, description:] is not an ObjectType`

**Comment by CNAChino** [comment]
@rajankit296 looking at this issue, will release a fix for this

**Comment by rajankit296** [comment]
Thanks @CNAChino  for the information. I will go though the doc and try to implement it.

**Comment by ashpak-shaikh** [comment]
@rajankit296 
Please try the below schema.

Service 1 Schema:

```
type Query { 
  resourceType: [ResourceType] 
}

type ResourceType @key(fields: "name") {
  name : String # unique key
  title: String
}
```

Service 2 Schema:

```
type ResourceType @key(fields: "name") {
  name : String 
  version: String
  description: String
}
```

Additionally, you will also need to 
1. Change the [serviceType](https://github.com/graph-quilt/graphql-orchestrator-java/blob/master/src/main/java/com/intuit/graphql/orchestrator/ServiceProvider.java#L34) to FEDERATION_SUBGRAPH. 
2. Both Service1 and Service2 are [Federation Compliant Subgraph Service](https://www.apollographql.com/docs/federation/subgraph-spec).
