### ISSUE TITLE
Migrate tests to Groovy: FieldResolverBatchSelectionSetSupplierLiteralsTest 

### ISSUE THREAD

**Issue by bhavinshah7** [graph-quilt/graphql-orchestrator-java#170]
**Is your feature request related to a problem? Please describe.**

Migrate unit tests in FieldResolverBatchSelectionSetSupplierLiteralsTest to use Spock framework. Some tests were migrated [here](https://github.com/intuit/graphql-orchestrator-java/pull/8/files) for reference.

Tests in groovy are easier to read. We don't need to offload our queries into separate resource files like in Java.
def query = """
query {
}
"""

More meaningful and easier to read method names
def "should produce result"() { }

Easier to write (implicit types, given/when/then)

**Comment by kulkarnianiket** [comment]
Hi, I would like to contribute to this.

**Comment by kulkarnianiket** [comment]
I already see this test file in groovy. 
https://github.com/graph-quilt/graphql-orchestrator-java/blob/master/src/test/groovy/com/intuit/graphql/orchestrator/fieldresolver/FieldResolverBatchSelectionSetSupplierLiteralsSpec.groovy
Is this still an issue?

**Comment by CNAChino** [comment]
Hi @kulkarnianiket thanks for looking into this.  You're right this has been migrated already.  We will delete this file and close the Issue

**Comment by CNAChino** [comment]
Hi @kulkarnianiket you might want to look into this issue:
https://github.com/graph-quilt/graphql-orchestrator-java/issues/169
